export const CREATE_BOARD = 'CREATE_BOARD';
export const CURRENT_BOARD = 'CURRENT_BOARD';
export const ADD_COLUMN_TO_BOARD = 'ADD_COLUMN_TO_BOARD';

export const ADD_LIST_ITEM_TO_COLUMN = 'ADD_LIST_ITEM_TO_COLUMN';
export const REODER_LIST_ITEM_TO_COLUMN = 'REODER_LIST_ITEM_TO_COLUMN';
